### ISSUE TITLE
Loading indicator displays when 0 results returned

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/search-interface#103]
![image](https://user-images.githubusercontent.com/18539827/214919146-7a7e4b9f-748f-42dc-8964-31e63b068946.png)

**Comment by juliacollins** [comment]
A fix is available for testing at https://integration.nsidc.org/data/search, if you're interested!

**Comment by MattF-NSIDC** [comment]
Looks great, nice work! :partying_face:

**Comment by juliacollins** [comment]
Fix is deployed to production!
